export const ICONS = {
  MENU_ANIMATED: 'line-md:menu',
  CLOSE: 'mdi:close',
  CLOSE_ANIMATED: 'line-md:menu-to-close-transition',
  DEFAULT_MENU: 'line-md:pause-to-play-filled-transition',
  LIGHT_MODE: 'line-md:sunny-loop',
  DARK_MODE: 'line-md:sunny-outline-to-moon-alt-loop-transition',
  DASHBOARD: 'ic:outline-dashboard',
  STAGE: 'pajamas:stage-all',
  ATTACK: 'ic:outline-security',
  LOADING: 'svg-spinners:3-dots-move',
  COMPONENTS: 'mynaui:components',
  UP_FILL_ROUNDED: 'eva:arrow-up-fill',
  DOWN_FILL_ROUNDED: 'eva:arrow-down-fill',
  MASTER: 'oui:app-devtools',
  SEARCH: 'ic:baseline-search',
};
